name: Run tests

on:
  push:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Run tests
        run: |
          npm install
          pip install -r requirements.txt
          npm test
